# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class GStack < Formula
  desc "G-stack is a cli util to simplify creating stacked branches and pull requests on"
  homepage "https://github.com/Bendzae/g-stack"
  url "https://github.com/Bendzae/g-stack/archive/refs/tags/0.0.2.tar.gz"
  sha256 "e9c20925e90391c9ec837d813fc7512343ca390d1591051a860ca9232f0bd15a"
  license "MIT"

  depends_on "bash" => :build
  depends_on "gcc"

  on_macos do
  end

  def install
    bin.install "g-stack" => "gs"
  end
end
