# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class GStack < Formula
  desc "Cli util to simplify creating stacked branches and pull requests on github"
  homepage "https://github.com/Bendzae/g-stack"
  url "https://github.com/Bendzae/g-stack/archive/refs/tags/0.0.2.tar.gz"
  sha256 "fae8b696397245d98d8dbb2ca434912f71d17bddcf18a0b00e1b243f8d64d785"
  license "MIT"

  def install
    bin.install "gstack" => "gs"
  end
end
