# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Gstack < Formula
  desc "Cli util to simplify creating stacked branches and pull requests on github"
  homepage "https://github.com/Bendzae/g-stack"
  url "https://github.com/Bendzae/gstack/releases/download/0.0.2/gstack-0.0.2-aarch64-apple-darwin.tar.gz"
  sha256 "4762cafff915776ea6778b2d5f5d57785d7581e69fea08e495b0353d7c648837"
  license "MIT"

  def install
    bin.install "gstack" => "gs"
  end
end
