name: Bump

on:
  workflow_dispatch:

jobs:
  - name: Bump packages
    uses: Homebrew/actions/bump-packages@master
    with:
      # Custom GitHub access token with only the 'public_repo' scope enabled
      token: ${{secrets.TOKEN}}
