name: Bump

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:

jobs:
  update:
    name: Bump packages
    uses: Homebrew/actions/bump-packages@master
    with:
      # Custom GitHub access token with only the 'public_repo' scope enabled
      token: ${{secrets.TOKEN}}
